# Generated by Django 4.2.3 on 2023-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='One-off default', max_length=50),
            preserve_default=False,
        ),
    ]
