# Generated by Django 4.2.3 on 2023-08-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_rename_date_review_created_at_remove_review_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'english'), ('Bulgarian', 'bulgarian'), ('German', 'german'), ('French', 'french')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
