# Generated by Django 4.2.3 on 2023-08-11 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_book_dimensions_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ave_rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
