# Generated by Django 4.2.3 on 2023-08-11 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_book_ave_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ave_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
