# Generated by Django 4.2.3 on 2023-08-12 14:36

import bookworm.bookstore.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_author_name_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(null=True, validators=[bookworm.bookstore.validators.validate_isbn_length]),
        ),
    ]
