# Generated by Django 4.2.3 on 2023-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='sold_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
